# Generated by Django 3.0.5 on 2020-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_auto_20200414_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UserGroup',
        ),
    ]
