# Generated by Django 3.0.5 on 2020-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_auto_20200414_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name_of_group',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
