# Generated by Django 3.0.5 on 2020-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0006_auto_20200415_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='data_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='diagrams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='queue_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='smart_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='voice_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='voice_stats',
            field=models.BooleanField(default=False),
        ),
    ]
